project:
  type: website
  preview:
    port: 4200
  output-dir: docs

execute:
  freeze: auto

resources: 
  - "CNAME"

website:

  favicon: assets/danilo.png
  title: "Danilo Toapanta"
  site-url: "https://www.danilotpnta.com"
  description: Personal website, portfolio and blog
  image: assets/danilo.png
  back-to-top-navigation: false
#  site-path: "/danilotpnta.github.io/"  # when commented 404.html renders correctly
  # site-url: https://danilotpnta.github.io/
  
  search: 
    location: navbar
    type: overlay
  navbar:
    title: "<span id='danilo_topanta_brand'> Danilo Toapanta</span> <a id='mysite' class='mysite' href= '../../../../../sites/'>MySites</a>"
    # title: "<span id='danilo_topanta_brand'> Danilo Toapanta</span>"
    # logo-href: ../../../../../../../../../../../sites/
    right:
      - text: "<span id='home-welcome-msg'>Home</span>"
        file: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      # - text: "Writing"
      #   menu:
      #   - text: Blog
      #     href: blog/index.qmd
      #   - text: Notes
      #     href: notes/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "About"
        file: about/index.qmd
      - icon: github
        href: https://github.com/danilotpnta?tab=repositories
        target: _blank
      # - icon: braces
        # href: dev/ # Replace for actual url
      # - icon: search 
        # href: "#top"
      # - icon: moon
      #   href: about/qmd


  page-footer:
    center: 
      # - text: "Mantained by Danilo Toapanta 
      #        [[Newsletter](coming-soon.qmd)]{.a-padding-footer .disable-link-underline}
      #        [[RSS](docs/sitemap.xml)]{.a-padding-footer .disable-link-underline}
      #        "
      - text: "[Mantained by Danilo Toapanta]{.footerDaniloToapanta}"
        file: about/index.qmd
      - text: "Newsletter"
        file: coming-soon.qmd
      - text: "RSS"
        file: docs/sitemap.xml
      # - icon: github
      #   href: https://github.com/
    # center: "Mantained by Danilo Toapanta </br> [[Source](https://github.com/danilotpnta/danilotpnta.github.io)]{.grey-link-underline} | License "
#    right:
#      - icon: github
#        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com/

format:
  html:
    page-layout: article
    theme:
      light: [default, styling/theme-light.scss]
      dark:  [default, styling/theme-dark.scss]
    grid:
      body-width: 750px
      sidebar-width: 250px
    toc: true
    toc-location: left
    code-link: true
    code-fold: show
    highlight-style:
      # light: styling/atom-one-light.theme
      light: styling/arrow-light.theme
      dark: styling/dracula.theme
    include-in-header:
      - file: _partials/icons/add-icons.html
      - text: |
          <link rel = "shortcut icon" href = "../../../../../../../../../../../assets/danilo.ico" />
    include-after-body:
      - file: _partials/search.html
