project:
  type: website
  preview:
    port: 4200
  output-dir: docs

execute:
  freeze: auto

resources: 
  - "CNAME"

website:

  image: assets/images/danilo.png
  favicon: assets/images/danilo.png
  title: "Danilo Toapanta"
  description: Personal website, portfolio and blog
  # site-path: "/danilotpnta.github.io/"  # when commented 404.html renders correctly
  # site-url: https://danilotpnta.github.io/
  site-url: "https://www.danilotpnta.com"
  repo-url: "https://github.com/danilotpnta/danilotpnta.github.io/"
  repo-actions: [source, edit, issue]
  # repo-branch: "gh-pages"

  announcement: 
    icon: info-circle
    dismissable: false
    content: "**Let op** - This website is undergoing scheduled maintenance"
    type: primary
    position: above-navbar
  
  page-navigation: true
  back-to-top-navigation: false

  search: 
    location: navbar
    type: overlay

  navbar:
    title: "<span id='danilo_topanta_brand'> Danilo Toapanta</span> <a id='mysite' class='mysite' href= '/site-ver-hist/'>v1.3</a>"
    right:
      - text: "<span id='home-welcome-msg'>Home</span>"
        file: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "About"
        file: about/index.qmd
      - icon: github
        href: https://github.com/danilotpnta?tab=repositories
        target: _blank

  page-footer:
    left:
      - text: "[© 2024 Danilo Toapanta]{.footerDaniloToapanta}"
        file: about/index.qmd
    center: 
      - text: "Privacy"
        file: privacy/index.qmd
      - text: "Contact"
        file: contact/index.qmd
      - text: "License"
        file: license/index.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/danilotpnta/
      - icon: twitter
        href: https://x.com/DaniloToapnta
      - icon: rss-fill
        file: docs/sitemap.xml

    
format:
  html:
    html-math-method: mathjax
    page-layout: article
    theme:
      light: [default, styling/theme-light.scss]
      dark:  [default, styling/theme-dark.scss]
    grid:
      body-width: 750px
      sidebar-width: 250px
    toc: true
    toc-location: left
    code-link: true
    code-fold: show
    highlight-style:
      light: styling/arrow-light.theme
      dark: styling/dracula.theme
    include-in-header:
      - text: |
            <script>
            window.MathJax = {
              tex: {
                tags: 'ams'
              }
            };
            </script>
      - file: _partials/icons/add-icons.html
    include-after-body:
      - file: _partials/search.html