---
title: "When you get older"
description: ""
date: "2023-09-03"
categories: [All, Poems, TAGS, Spanish]
navbar: false
css: ../css/index-poems.css
---
<span class='by-danilo-toapanta'>by <a href='../../about/'>Danilo Toapanta</a> </span>

<div style="font-weight:300;">
<a href="../../blog/" style="text-decoration: none;" >Blog </a> <a style="text-decoration: none; pointer-events: none; font-weight: 250;" href="">></a> <a href="../../blog/#category=Poems" style="text-decoration: none;" >Poems</a>
</div>

<div class="poem-text">
When you get older my son

Your hands start to become like raisins

Your heart beats like one of those boats

but not like those new ones.

<pre></pre>

When you get older son

Your memories start to fade 

As with your energy every day

You wonder son, how are my children doing

And in a cozy chair your find yourself

lost navigating in your memories

those years where your hands were not raisins.

<pre></pre>

For that reason my son

if you see me agitated

fragile like a leaf of autumn

remember son

your father is just 

like a brand new boat

but not like those new ones

it is just a boat,

a boat that continues navigating

with more wisdom and firm pace.

<pre></pre>

Oh son, do not panic. If one day this boat

has decided to take its last ship

That day my son you will know this ship

has found the most valuable and precious secret

And that day my son

I will pass on you

before my wood sinks and 

my sails float in the sea of life.

<pre></pre>

Be certain son, 

that day you will then be armoured for a war

and from the depth seas

I will command you and guide your way

exactly like my father did it

a couple of decades ago.


<p style=" padding-top: 1.5em; text-align: right; color: gray; ">
With love to Marcelo and Valerio Saico 
</p>


</p>






































